Update CI/CD workflow

diff --git a/.github/workflows/deploy-target-group-prod-backend.yml b/.github/workflows/deploy-target-group-prod-backend.yml
--- a/.github/workflows/deploy-target-group-prod-backend.yml
+++ b/.github/workflows/deploy-target-group-prod-backend.yml
@@ -1,4 +1,4 @@
-name: Build & Deploy Backend to Test Environment
+name: Build & Deploy Backend to Production Environment
 
 on:
   push:
@@ -10,13 +10,13 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      - name: Checkout repository
-        uses: actions/checkout@v2
+      - name: Checkout code
+        uses: actions/checkout@v4
 
       - name: Setup Java
         uses: actions/setup-java@v2
         with:
-          distribution: temurin # Рекомендуемый дистрибутив
+          distribution: temurin
           java-version: 21
           java-package: jdk
           architecture: x64
@@ -25,21 +25,27 @@ jobs:
         run: mvn clean install -DskipTests
 
       - name: Configure AWS credentials
-        uses: aws-actions/configure-aws-credentials@v1
+        uses: aws-actions/configure-aws-credentials@v2
         with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: ${{ vars.AWS_REGION }}
 
-      - name: Login to Amazon ECR
-        uses: aws-actions/amazon-ecr-login@v1
+      - name: Login to Amazon ECR via AWS CLI
+        run: |
+          aws ecr get-login-password --region "${{ vars.AWS_REGION }}" | docker login --username AWS --password-stdin "${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com"
 
-      - name: Build and push Docker image
-        uses: docker/build-push-action@v2
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v2
+        with:
+          driver: docker-container
+
+      - name: Build and push Docker Server image
+        uses: docker/build-push-action@v4
         with:
           context: .
           push: true
-          tags: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/${{ vars.PROD_TEST_ECR_REPOSITORY }}:${{ vars.IMAGE_TAG }}
+          platforms: linux/amd64
           build-args: |
             DATABASE_PATH=${{ vars.DATABASE_PATH }}
             DATABASE_USER=${{ secrets.DATABASE_USER }}
@@ -62,6 +68,11 @@ jobs:
             COGNITO_SECRET_ACCESS_KEY=${{ secrets.COGNITO_SECRET_ACCESS_KEY }}
             IMAGE_TAG=${{ vars.IMAGE_TAG }}
             ECR_REPOSITORY=${{ vars.PROD_TEST_ECR_REPOSITORY }}
+          tags: |
+            ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/${{ vars.ECR_CLIENT_REPOSITORY }}:${{ github.ref_name }}-latest
+            ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/${{ vars.ECR_CLIENT_REPOSITORY }}:latest
+          cache-from: type=gha
+          cache-to: type=gha,mode=max
 
   deploy:
     needs: build-and-push
@@ -69,171 +80,113 @@ jobs:
 
     steps:
       - name: Checkout repository
-        uses: actions/checkout@v2
+        uses: actions/checkout@v4
 
       - name: Configure AWS credentials
-        uses: aws-actions/configure-aws-credentials@v1
+        uses: aws-actions/configure-aws-credentials@v2
         with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: ${{ vars.AWS_REGION }}
 
-      - name: Set up check_command_status script
-        run: |
-          cat <<- 'EOF' > /tmp/check_command_status.sh
-          #!/bin/bash
-          check_command_status () {
-            local command_id=$1
-            local instance=$2
-            local status="Pending"
-            while [[ "$status" == "Pending" || "$status" == "InProgress" ]]; do
-              status=$(aws ssm get-command-invocation --command-id "$command_id" --instance-id "$instance" --query 'Status' --output text 2>/dev/null)
-              if [ -z "$status" ]; then
-                status="Pending"
-              fi
-              echo "Command $command_id status on instance $instance: $status"
-              sleep 5
-            done
-            output=$(aws ssm get-command-invocation --command-id "$command_id" --instance-id "$instance" --query 'StandardOutputContent' --output text)
-            error_output=$(aws ssm get-command-invocation --command-id "$command_id" --instance-id "$instance" --query 'StandardErrorContent' --output text)
-            if [[ "$status" != "Success" ]]; then
-              echo "Command $command_id failed with status: $status"
-              echo "Standard Error:"
-              echo "$error_output"
-              exit 1
-            else
-              echo "Command $command_id succeeded with status: $status"
-              echo "Standard Output:"
-              echo "$output"
-            fi
-          }
-          export -f check_command_status
-          EOF
-
       - name: Get EC2 instances in Target Group
         id: get_instances
         run: |
-          instances=$(aws elbv2 describe-target-health --target-group-arn ${{ secrets.PROD_BACKEND_TARGET_GROUP_ARN }} --query 'TargetHealthDescriptions[*].Target.Id' --output text)
+          instances=$(aws elbv2 describe-target-health --target-group-arn ${{ secrets.PROD_BACKEND_TARGET_GROUP_ARN  }} --query 'TargetHealthDescriptions[*].Target.Id' --output text)
           echo "Instances found: $instances"
           echo "instances=$instances" >> $GITHUB_OUTPUT
 
-      - name: Pull the latest Docker image
-        env:
-          AWS_REGION: ${{ vars.AWS_REGION }}
-          IMAGE_FULL_NAME: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/${{ vars.PROD_TEST_ECR_REPOSITORY }}:${{ vars.IMAGE_TAG }}
+      - name: Create wait_for_ssm_command.sh script
+        shell: bash
         run: |
-          source /tmp/check_command_status.sh
-          instances="${{ steps.get_instances.outputs.instances }}"
-          for instance in $instances
-          do
-            echo "Deploying to instance: $instance"
-
-            # Определяем команду
-            command="docker pull ${IMAGE_FULL_NAME}"
-            echo "Pull Command: \"$command\""
-
-            # Отправляем команду через SSM
-            command_id=$(aws ssm send-command \
-              --instance-ids "$instance" \
-              --document-name "AWS-RunShellScript" \
-              --parameters '{"commands": [
-                "'"${command}"'"
-              ]}' \
-              --region "${AWS_REGION}" \
-              --query "Command.CommandId" \
-              --output text)
-            echo "Pull Command ID: $command_id"
-
-            # Проверяем статус выполнения команды
-            check_command_status "$command_id" "$instance"
+          cat << 'EOF' > wait_for_ssm_command.sh
+          #!/bin/bash
+          command_id=$1
+          instance_id=$2
+          status="Pending"
+          while [[ "$status" == "Pending" || "$status" == "InProgress" ]]; do
+            status=$(aws ssm get-command-invocation --command-id "$command_id" --instance-id "$instance_id" --query 'Status' --output text 2>/dev/null)
+            if [ -z "$status" ]; then
+              status="Pending"
+            fi
+            echo "Command $command_id status on instance $instance_id: $status"
+            sleep 5
           done
+          # После завершения команды выводим стандартный вывод и ошибки
+          output=$(aws ssm get-command-invocation --command-id "$command_id" --instance-id "$instance_id" --query 'StandardOutputContent' --output text)
+          error_output=$(aws ssm get-command-invocation --command-id "$command_id" --instance-id "$instance_id" --query 'StandardErrorContent' --output text)
+          if [[ "$status" != "Success" ]]; then
+            echo "Command $command_id failed with status: $status"
+            echo "Standard Error:"
+            echo "$error_output"
+            exit 1
+          else
+            echo "Command $command_id succeeded with status: $status"
+            echo "Standard Output:"
+            echo "$output"
+          fi
+          EOF
+          chmod +x wait_for_ssm_command.sh
 
-      - name: Stop running containers
+      - name: Deploy to Instances
         env:
           AWS_REGION: ${{ vars.AWS_REGION }}
+          IMAGE_FULL_NAME: '${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/${{ vars.PROD_TEST_ECR_REPOSITORY }}:${{ github.ref_name }}-latest'
         run: |
-          source /tmp/check_command_status.sh
           instances="${{ steps.get_instances.outputs.instances }}"
-          for instance in $instances
-          do
+          for instance in $instances; do
             echo "Deploying to instance: $instance"
 
-            # Определяем команду
-            command="cd /home/ec2-user/app && docker-compose down"
-            echo "Stop Command: \"$command\""
-
-            # Отправляем команду через SSM
+            # Pull latest Docker image
+            echo "Pulling Docker image on instance: $instance"
             command_id=$(aws ssm send-command \
               --instance-ids "$instance" \
               --document-name "AWS-RunShellScript" \
               --parameters '{"commands": [
-                "'"${command}"'"
+                "aws ecr get-login-password --region '"${AWS_REGION}"' | docker login --username AWS --password-stdin '"${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com"'",
+                "cd /home/ec2-user/app && docker pull '"${IMAGE_FULL_NAME}"'"
               ]}' \
               --region "${AWS_REGION}" \
               --query "Command.CommandId" \
               --output text)
-            echo "Stop Command ID: $command_id"
+            ./wait_for_ssm_command.sh "$command_id" "$instance"
 
-            # Проверяем статус выполнения команды
-            check_command_status "$command_id" "$instance"
-          done
-
-      - name: Start containers
-        env:
-          AWS_REGION: ${{ vars.AWS_REGION }}
-        run: |
-          source /tmp/check_command_status.sh
-          instances="${{ steps.get_instances.outputs.instances }}"
-          for instance in $instances
-          do
-            echo "Deploying to instance: $instance"
-
-            # Определяем команду
-            command="cd /home/ec2-user/app && docker-compose up -d"
-            echo "Start Command: \"$command\""
-
-            # Отправляем команду через SSM
+            # Stop running containers
+            echo "Stopping containers on instance: $instance"
             command_id=$(aws ssm send-command \
               --instance-ids "$instance" \
               --document-name "AWS-RunShellScript" \
               --parameters '{"commands": [
-                "'"${command}"'"
+                "cd /home/ec2-user/app && docker-compose down"
               ]}' \
               --region "${AWS_REGION}" \
               --query "Command.CommandId" \
               --output text)
-            echo "Start Command ID: $command_id"
+            ./wait_for_ssm_command.sh "$command_id" "$instance"
 
-            # Проверяем статус выполнения команды
-            check_command_status "$command_id" "$instance"
-          done
-
-      - name: Remove unused Docker images
-        env:
-          AWS_REGION: ${{ vars.AWS_REGION }}
-        run: |
-          source /tmp/check_command_status.sh
-          instances="${{ steps.get_instances.outputs.instances }}"
-          for instance in $instances
-          do
-            echo "Deploying to instance: $instance"
-
-            # Определяем команду
-            command="docker image prune -f"
-            echo "Prune Command: \"$command\""
-
-            # Отправляем команду через SSM
+            # Start containers
+            echo "Starting containers on instance: $instance"
             command_id=$(aws ssm send-command \
               --instance-ids "$instance" \
               --document-name "AWS-RunShellScript" \
               --parameters '{"commands": [
-                "'"${command}"'"
+                "cd /home/ec2-user/app && docker-compose up -d"
               ]}' \
               --region "${AWS_REGION}" \
               --query "Command.CommandId" \
               --output text)
-            echo "Prune Command ID: $command_id"
+            ./wait_for_ssm_command.sh "$command_id" "$instance"
 
-            # Проверяем статус выполнения команды
-            check_command_status "$command_id" "$instance"
+            # Remove unused Docker images
+            echo "Pruning Docker images on instance: $instance"
+            command_id=$(aws ssm send-command \
+              --instance-ids "$instance" \
+              --document-name "AWS-RunShellScript" \
+              --parameters '{"commands": [
+                "docker image prune -f"
+              ]}' \
+              --region "${AWS_REGION}" \
+              --query "Command.CommandId" \
+              --output text)
+            ./wait_for_ssm_command.sh "$command_id" "$instance"
           done
